import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import BootstrapClient from "./components/BootstrapClient";
import '@fortawesome/fontawesome-free/css/all.min.css'
import Header from "./components/Header";
import Footer from "./components/Footer";
import './styles/main.css'

export const metadata: Metadata = {
  title: "SafariSim",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Header/>
        {children}
        <BootstrapClient/>
        <Footer/>
      </body>
    </html>
  );
}